targets:
  $default:
    builders:
      json_serializable:
        generate_for:
          - lib/application/dto/**.dart
      
      freezed:
        generate_for:
          - lib/application/dto/**.dart
      
      injectable_generator:injectable_generator:
        generate_for:
          - lib/core/di/injection_container.dart
