name: serenithy_app
description: "Serenithy mobile application following hexagonal architecture"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=3.13.0"

dependencies:
  flutter:
    sdk: flutter

  # UI & Material Design
  cupertino_icons: ^1.0.6
  flutter_screenutil: ^5.9.0

  # State Management
  flutter_bloc: ^8.1.3
  bloc_concurrency: ^0.2.2

  # Dependency Injection
  get_it: ^7.6.4
  injectable: ^2.3.2

  # HTTP Client & Networking
  dio: ^5.3.2
  connectivity_plus: ^5.0.1

  # JSON Serialization
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1

  # Local Storage
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Functional Programming
  dartz: ^0.10.1

  # Utilities
  intl: ^0.18.1
  equatable: ^2.0.5
  logger: ^2.0.2+1

  # Environment Configuration
  flutter_dotenv: ^5.1.0

  # Navigation
  go_router: ^12.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting
  flutter_lints: ^3.0.0
  very_good_analysis: ^5.1.0

  # Code Generation
  build_runner: ^2.4.7
  injectable_generator: ^2.4.1
  json_serializable: ^6.7.1
  freezed: ^2.4.6
  hive_generator: ^2.0.1

  # Testing
  bloc_test: ^9.1.4
  mocktail: ^1.0.1

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/fonts/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
